ALTER TABLE TBLSCHOOL ADD CONSTRAINT FK_SCHOOLBUILDINGID
FOREIGN KEY (SCHOOLID) REFERENCES TBLBUILDING (BUILDINGDEPARTMENTID)


DROP TABLE TBLBUILDING

select * from TBLBUILDING

CREATE TABLE TBLBUILDING
(
BUILDINGDEPARTMENTID INT CONSTRAINT PK_BUILDINGDEPARTMENTID PRIMARY KEY   NOT NULL  ,
BUILDINGADDRESS VARCHAR(MAX),
BUILDINGNUMBEROFROOMS INT NOT NULL
)

alter table tblbuilding add  CREATEDON DATETIME NOT NULL DEFAULT GETDATE() 
alter table tblbuilding add MODIFIEDON DATETIME 
sp_depends TBLBUILDING

sp_who

begin tran

insert into TBLBUILDING (BUILDINGDEPARTMENTID,BUILDINGADDRESS,BUILDINGNUMBEROFROOMS) values (1,'1234 mountain house tracy',1001)
insert into tblbuilding(BUILDINGDEPARTMENTID,BUILDINGADDRESS,BUILDINGNUMBEROFROOMS) values(2,'abcd',1002)
rollback

select * from TBLBUILDING