SELECT * FROM TBLSTUDENT
ALTER TABLE TBLSTUDENT ADD CONSTRAINT DT_RANGE_DOB 
check (STUDENTDOB<=getdate())

DELETE FROM TBLSTUDENT WHERE STUDENTID=12

INSERT INTO TBLSTUDENT (
STUDENTGENDER,
STUDENTDOB,
STUDENTFIRST,
STUDENTLAST,
STUDENTMIDDLE,
STUDENTSUBURB,
STUDENTADDRESS,
STUDENTEMAIL) VALUES ('MALE',GETDATE()-1,'RAM','ABC','ASD','ASDADSV','ewfewrab','AFERV@GMAIL.COM')

TRUNCATE TABLE TBLSTUDENT 