CREATE TABLE TBLSTAFF
(
STAFFID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
STAFFDEPARTMENTID INT NOT NULL,
STAFFGENDER VARCHAR(10) NOT NULL,
STAFFDOB DATE NOT NULL,
STAFFFIRST VARCHAR(100) NOT NULL,
STAFFLAST VARCHAR(100) NOT NULL,
STAFFADDRESS VARCHAR(MAX) NOT NULL,
STAFFEMAIL VARCHAR(100) NOT NULL,
STAFFSALARY INT NOT NULL
)