CREATE TABLE TBLSTUDENTPAYMENT
(
PAYMENTID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
PAYMENTSTUDENTID INT NOT NULL,
PAYMENTENROLMENTID INT NOT NULL,
PAYMENTAMOUNT INT NOT NULL,
PAYMENTDATE DATE 
)


select * from sys.objects where type='P'